### PR TITLE
Add IDE related folder paths to ignore list

### PR DESCRIPTION
**Pull request by buttercrab**

### CODE REVIEW

**Review by stevehan00 — APPROVED** [review]

**Review by sboh1214 — APPROVED** [review]
Good commit, but it'll be better if we clarify that they are folders.
```
.idea/
.vscode/
```
And @utilForever, is there any changes needed in coverage Github Actions?

**Review by utilForever — CHANGES_REQUESTED** [review]
I modified the title. Also, you should change
1. Please write the description.
2. Please create a branch from this repo, not fork. (next time)

**Comment by utilForever** [comment]
@sboh1214 Nope, this failure is caused by the missing secure token `CODECOV_TOKEN`.

**Comment by buttercrab** [comment]
I'll reopen this with branch and remove fork.

**Pull request closed without merging**
